<?php include '../vue-php-Botml/header.inc.php'; ?>


<div class="delete">
	<img src="/3WA/BOTML/ressources-Botml/image/pics/there-are-many-things-that-need-to-be-erased.jpg" alt="Rat Boy Genius">
	
<br>
	
	<a class="return" href="index-crud.php">Retour au C.R.U.D</a>
	
</div>
	<audio id="audio" autoplay ><source src="../ressources-Botml/audio/There-are-many-things-that-need-to-be-erased.mp3" type="audio/mp3"></audio>
	
	<script src="../JS-BOTML/audio-trigger.js"></script>
	


